TEST: Add eos token tests for the HTTP protocol

diff --git a/test/eos-https-functional-test b/test/eos-https-functional-test
--- a/test/eos-https-functional-test
+++ b/test/eos-https-functional-test
@@ -28,7 +28,7 @@
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
 
 
-usage() { echo '''Usage: eos-https-func-tests [-h|--host <host>[:<port>| (-p|--port) <port>]]
+usage() { echo '''Usage: eos-https-functional-test [-h|--host <host>[:<port>| (-p|--port) <port>]]
                            [-c|--cert <x509 certificate>]
                            [-k|--key <x509 key>]
                            [-C|--cacert <CA certificate>]
@@ -36,14 +36,14 @@ usage() { echo '''Usage: eos-https-func-tests [-h|--host <host>[:<port>| (-p|--p
                            [-t|--dir <directory on which to run tests>]
                            [-v|--verbose]
 
-                           [-h|--help] - usage & exit
+                           [--help] - usage & exit
 '''; }
 
 # Parser from: https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
 usage_error () { echo >&2 "$(basename "$0"):  $1"; exit 2; }
 assert_argument () { test "$1" != "$EOL" || usage_error "$2 requires an argument"; }
 
-port="${EOS_HTTPS_PORT:-443}" 
+port="${EOS_HTTPS_PORT:-443}"
 host=$(hostname -f)
 cacert="/etc/grid-security/certificates/rootCA.pem"
 capath="$(dirname "${cacert}")"
@@ -69,13 +69,13 @@ if [ "$#" != 0 ]; then
       -C|--cacert)  assert_argument "$1" "$opt"; cacert="${1}" && capath="$(dirname "${cacert}")"; shift;;
       -P|--capath)  assert_argument "$1" "$opt"; capath="${1}"; shift;;
       -t|--dir) assert_argument "$1" "$opt"; testdir="${1}"; shift;;
-       
-      -h|--help) usage; exit 0;;
+
+      --help) usage $0; exit 0;;
 
       # Arguments processing. You may remove any unneeded line after the 1st.
       -|''|[!-]*) set -- "$@" "$opt";;                                          # positional argument, rotate to the end
       --*=*)      set -- "${opt%%=*}" "${opt#*=}" "$@";;                        # convert '--name=arg' to '--name' 'arg'
-      -[!-]?*)    set -- "$(echo "${opt#-}" | sed 's    /g')" "$@";;     # convert '-abc' to '-a' '-b' '-c'
+      -[!-]?*)    set -- "$(echo "${opt#-}" | sed 's    /g')" "$@";;            # convert '-abc' to '-a' '-b' '-c'
       --)         while [ "$1" != "$EOL" ]; do set -- "$@" "$1"; shift; done;;  # process remaining arguments as positional
       -*)         usage_error "unknown option: '$opt'";;                        # catch misspelled options
       *)          usage_error "this should NEVER happen ($opt)";;               # sanity test for previous patterns
@@ -86,7 +86,7 @@ if [ "$#" != 0 ]; then
 fi
 
 echo "Results:"
-### X509 
+### X509
 # Returns 0 if successful, 1 if upload failed, 2 if download failed, 3 if both failed
 x509() {
   respUpload="$(curl -sS ${verbose} -I -L --capath "${capath}" --cert "${cert}" --cacert "${cacert}" --key "${key}" "https://${host}:${port}/${testdir}/helloworld.txt" --upload-file <(echo ola) | grep HTTP | tr -d '\r' | paste -sd'+')"
@@ -96,7 +96,7 @@ x509() {
 
   [[ $respUpload == "HTTP/1.1 307 TEMPORARY_REDIRECT+HTTP/1.1 201 CREATED" ]]
   upcode=$?
-	[[ $respDownload == "HTTP/1.1 200 OK" ]]
+        [[ $respDownload == "HTTP/1.1 200 OK" ]]
   downcode=$?
 
   return  $((2#$downcode$upcode))
@@ -110,14 +110,14 @@ macaroon() {
     # certificate and private key
     export X509_USER_CERT=${cert}
     export X509_USER_KEY=${key}
-    
+
     # Use the macaroon-init tool to request a macaroon: yum install x509-scitokens-issuer-client --enablerepo="osg-development"
     macaroon-init -v foo >/dev/null 2>&1 || { echo -e >&2 "I require macaroon-init but it's not installed.  Aborting.\n"
     "yum install https://repo.opensciencegrid.org/osg/3.4/osg-3.4-el$(uname -r | awk -F '.' '$0=$(NF-1)')-release-latest.rpm\n"
     "yum install --enablerepo=osg-development -y x509-scitokens-issuer-client";
     exit 256;
     }
-    
+
     export MACAROON="$(macaroon-init https://${host}:${port}/${testdir}/ 60 UPLOAD,DOWNLOAD)"
     respMacaroonUpload="$(curl -I -sS ${verbose} -L -H "Authorization: Bearer ${MACAROON}" https://${host}:${port}${testdir}/helloworld-macaroon.txt --upload-file <(echo ola) | grep HTTP | tr -d '\r' | paste -sd'+')"
     echo -e "\tmacaroon upload -> ${respMacaroonUpload}"
@@ -180,20 +180,69 @@ tcp() {
     [[ ${respTpcPush} == "HTTP/1.1 307 Temporary Redirect+HTTP/1.1 201 Created" ]]
     tpcpushcode=$?
 
-    return $(( 2#$tpcpushcode$tpcpullcode))
+    return $((2#$tpcpushcode$tpcpullcode))
 }
 
+# EOS token
+eostoken() {
+    eos space config default space.token.generation=1
+    EXPIRE=`date +%s`; LATER=$(($EXPIRE+300));
+    export EOS_RW_TOKEN=`XrdSecPROTOCOL=gsi eos root://${host}:1094/ token --path ${testdir}/ --tree --permissions rwx --expires $LATER`
+
+    if [[ $? -ne 0 ]]; then
+        echo -e '\terror: eos rw token command failed'
+        return 1
+    fi
+
+    export EOS_RO_TOKEN=`XrdSecPROTOCOL=gsi eos root://${host}:1094/ token --path ${testdir}/ --tree --permissions rx --expires $LATER`
+
+    if [[ $? -ne 0 ]]; then
+        echo -e '\terror: eos ro token command failed'
+        return 1
+    fi
+
+    respEosTokenRwUpload="$(curl -I -sS ${verbose} -L -H "Authorization: Bearer ${EOS_RW_TOKEN}" https://${host}:${port}${testdir}/helloworld-eostoken.txt --upload-file <(echo ola-token) | grep HTTP | tr -d '\r' | paste -sd'+')"
+    echo -e "\teostoken rw upload -> ${respEosTokenRwUpload}"
+    [[ $respEosTokenRwUpload == "HTTP/1.1 307 TEMPORARY_REDIRECT+HTTP/1.1 201 CREATED" ]]
+    eostoken_rw_up=$?
+
+    respEosTokenRwDownload="$(curl -I -sS ${verbose} -L -H "Authorization: Bearer ${EOS_RW_TOKEN}" https://${host}:${port}${testdir}/helloworld-eostoken.txt|grep HTTP | tr -d '\r' | paste -sd'+')"
+    echo -e "\teostoken rw download -> ${respEosTokenRwDownload}"
+    [[ $respEosTokenRwDownload == "HTTP/1.1 200 OK" ]]
+    eostoken_rw_down=$?
+
+    respEosTokenRoDownload="$(curl -I -sS ${verbose} -L -H "Authorization: Bearer ${EOS_RO_TOKEN}" https://${host}:${port}${testdir}/helloworld-eostoken.txt|grep HTTP | tr -d '\r' | paste -sd'+')"
+    echo -e "\teostoken ro download -> ${respEosTokenRoDownload}"
+    [[ $respEosTokenRoDownload == "HTTP/1.1 200 OK" ]]
+    eostoken_ro_down=$?
+
+    # Make destination directory read-only and try to upload with RO token
+    eos root://${host}/ chmod 500 ${testdir}
+    respEosTokenRoUpload="$(curl -I -sS ${verbose} -L -H "Authorization: Bearer ${EOS_RO_TOKEN}" https://${host}:${port}${testdir}/helloworld-eostoken-ro.txt --upload-file <(echo ola-token) | grep HTTP | tr -d '\r' | paste -sd'+')"
+    echo -e "\teostoken ro upload -> ${respEosTokenRoUpload}"
+    [[ $respEosTokenRoUpload == "HTTP/1.1 403 FORBIDDEN" ]]
+    eostoken_ro_up=$?
+
+    eos root://${host}/ chmod 750 ${testdir}
+    return $((2#$eostoken_rw_up$eostoken_rw_down$eostoken_ro_down$eostoken_ro_up))
+}
 
 x509
 x509code=$?
 echo "x509:"$x509code
 
-macaroon
-macarooncode=$?
-echo "macaroon:"$macarooncode
+# @todo(esindril) disabled for the moment since macaroon-init not available
+# any more from the osg repos
+#macaroon
+#macarooncode=$?
+#echo "macaroon:"$macarooncode
+
+eostoken
+eostokencode=$?
+echo "eostoken:"$eostokencode
 
 tcp
 tcpcode=$?
 echo "tpc:"$tcpcode
 
-exit $x509code$macarooncode$tcpcode
+exit $x509code$macarooncode$tcpcode$eostokencode
