CI/TESTS: Add fsck tests

diff --git a/test/eos-instance-test-ci b/test/eos-instance-test-ci
--- a/test/eos-instance-test-ci
+++ b/test/eos-instance-test-ci
@@ -1,6 +1,41 @@
 #!/bin/bash
 
-echo "Running MQ tests"
+# ******************************************************************************
+# EOS - the CERN Disk Storage System
+# Copyright (C) 2019 CERN/Switzerland
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# ******************************************************************************
+
+function usage() {
+  echo "usage: $(basename $0) --type docker/k8s <k8s_namespace>"
+  echo "       docker : script runs in a Docker based setup"
+  echo "       k8s    : script runs in a Kubernetes setup and requires a namespace argument"
+}
+
+# Check minimal input
+if [[ $# -lt 2 ]]; then
+  echo "error: invalid number of arguments"
+  usage
+  exit 1
+fi
+
+# Running FSCK tests
+echo "Runing FSCK tests ..."
+eos-fsck-test "$@"
+
+echo "Running MQ tests ..."
 eos-mq-tests eos-mq-test.eoscluster.cern.ch
 
 if [[ $? -ne 0 ]]; then
@@ -8,7 +43,7 @@ if [[ $? -ne 0 ]]; then
     exit 1
 fi
 
-echo "Running drain test ..."
+echo "Running drain tests ..."
 eos-drain-test localhost
 
 if [[ $? -ne 0 ]]; then
@@ -16,7 +51,7 @@ if [[ $? -ne 0 ]]; then
     exit 1
 fi
 
-echo "Running instance test ..."
+echo "Running instance tests ..."
 eos space quota default on
 eos-instance-test
 
