FST: FSCK: Update stripe_err check to detect overreplication in rain files
When checking for stripe_err, now verify all the different locations,
taking into account duplicate stripes. If the file is overreplicated,
mark duplicated stripes as invalid.

The RainMetaLayout::OpenPio had to be extended to make possible openning
a stripe with a replica index greater than the number of stripes in the
layout.

Overreplicated stripes for rain layouts are now dropped in the fsck repair job.

Add a function to copy files between containers for tests, preserving their xattrs.

diff --git a/test/eos-fsck-test b/test/eos-fsck-test
--- a/test/eos-fsck-test
+++ b/test/eos-fsck-test
@@ -57,7 +57,9 @@ function create_test_files() {
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_stripe_diff.dat &&
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_stripe_sz_err.dat &&
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_invalid_stripe_err.dat &&
-                     xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_invalid_stripe_err2.dat"
+                     xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_invalid_stripe_err2.dat &&
+                     xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_stripe_diff_over.dat &&
+                     xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_stripe_diff_over2.dat"
   FXID_D_MEM_SZ_DIFF=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/file_d_mem_sz_diff.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_M_MEM_SZ_DIFF1=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/file_m_mem_sz_diff1.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_M_MEM_SZ_DIFF2=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/file_m_mem_sz_diff2.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
@@ -73,6 +75,8 @@ function create_test_files() {
   FXID_RAIN_STRIPE_SZ=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_RAIN_DIR}/rain_stripe_sz_err.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_RAIN_INVALID_STRIPE=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_RAIN_DIR}/rain_invalid_stripe_err.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_RAIN_INVALID_STRIPE2=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_RAIN_DIR}/rain_invalid_stripe_err2.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
+  FXID_RAIN_DIFF_OVER=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_RAIN_DIR}/rain_stripe_diff_over.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
+  FXID_RAIN_DIFF_OVER2=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_RAIN_DIR}/rain_stripe_diff_over2.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
 
 
   # If any of the FXID_* variables are empty then we have a problem
@@ -90,7 +94,9 @@ function create_test_files() {
         -z "${FXID_RAIN_DIFF}"            ||
         -z "${FXID_RAIN_STRIPE_SZ}"       ||
         -z "${FXID_RAIN_INVALID_STRIPE}"  ||
-        -z "${FXID_RAIN_INVALID_STRIPE2}" ]]; then
+        -z "${FXID_RAIN_INVALID_STRIPE2}" ||
+        -z "${FXID_RAIN_DIFF_OVER}"       ||
+        -z "${FXID_RAIN_DIFF_OVER2}"      ]]; then
     echo "error: some of the fxids could not be retrieved"
     cleanup
     exit 1
@@ -280,6 +286,101 @@ function corrupt_rain_invalid_stripe2() {
   exec_cmd "eos-fst${FSID}" "eos-compute-blockxs ${LPATH}"
 }
 
+# Duplicate stripe to generate RAIN stripe error
+function corrupt_rain_stripe_diff_over() {
+  local CMD_OUT=$(exec_cmd eos-cli1 "eos fileinfo fxid:${FXID_RAIN_DIFF_OVER} -m --fullpath | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '{if (\$1 ==\"fsid\") {print \$2};}'")
+  local VECT_FSID=( $(echo "${CMD_OUT}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//') )
+  echo "Used locations: ${VECT_FSID[@]}"
+  local NEW_FSID=""
+  local FST_ONLINE=$(exec_cmd eos-mgm1 "eos fs ls | grep \"online\" | wc -l")
+
+  for (( i=1; i<=${FST_ONLINE}; i++ )); do
+    local found=false
+    for e in ${VECT_FSID[@]}; do
+      if [[ "$i" == "$e" ]]; then
+        found=true
+        break
+      fi
+    done
+    if [[ "${found}" == false ]]; then
+      NEW_FSID=$i
+      break
+    fi
+  done
+
+  if [[ "${NEW_FSID}" == "" ]]; then
+    echo "error: no new FSID found for replication command"
+    exit 1
+  fi
+
+  # Start by tagging the file on the new fst
+  exec_cmd eos-cli1 "eos -r 0 0 file tag ${EOS_RAIN_DIR}/rain_stripe_diff_over.dat +${NEW_FSID}"
+
+  # Get local path of source and local path of the destination directory
+  local CMD_OUT=$(exec_cmd eos-cli1 "eos fileinfo fxid:${FXID_RAIN_DIFF_OVER} -m --fullpath | sed -r 's/[[:alnum:]]+=/\n&/g'")
+  local SRC_LPATH=$(echo "${CMD_OUT}" | grep fsid="${VECT_FSID[0]}" -A1 | tail -n1 | sed -r -e 's/^fullpath=//' -e 's/[[:space:]]*$//')
+  local SRC_LDIR=$(echo "${SRC_LPATH}" | sed -r 's/[[:alnum:]]+$//')
+  local SRC_LFILE=$(echo "${SRC_LPATH}" | grep -oE '[[:alnum:]]+$')
+  local DST_LDIR=$(echo "${CMD_OUT}" | grep fsid="${NEW_FSID}" -A1 | tail -n1 | sed -r -e 's/^fullpath=//' -e 's/[[:alnum:]]+[[:space:]]*$//')
+  cp_file_with_xattr_cmd "eos-fst${VECT_FSID[0]}" "${SRC_LDIR}" "${SRC_LFILE}" "eos-fst${NEW_FSID}" "${DST_LDIR}"
+  cp_file_with_xattr_cmd "eos-fst${VECT_FSID[0]}" "${SRC_LDIR}" "${SRC_LFILE}.xsmap" "eos-fst${NEW_FSID}" "${DST_LDIR}"
+
+  # Force resync of fmd on new fst
+  exec_cmd eos-cli1 "eos -r 0 0 file verify fxid:${FXID_RAIN_DIFF_OVER} ${NEW_FSID} -resync"
+}
+
+# Duplicate stripe and corrupt another stripe to generate RAIN stripe error
+function corrupt_rain_stripe_diff_over2() {
+  # First corrupt one stripe
+  local CMD_OUT=$(exec_cmd eos-cli1 "eos fileinfo fxid:${FXID_RAIN_DIFF_OVER2} -m --fullpath | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '{if (\$1 ==\"fsid\" || \$1 ==\"fullpath\") {print \$2};}' | tail -n2")
+  local FSID=$(echo "${CMD_OUT}" | head -n1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
+  local LPATH=$(echo "${CMD_OUT}" | tail -n1)
+  exec_cmd "eos-fst${FSID}" "dd if=/dev/urandom of=${LPATH} bs=1 seek=5000 count=10 conv=notrunc"
+  exec_cmd "eos-fst${FSID}" "eos-compute-blockxs ${LPATH}"
+
+  # Then duplicate another one
+  local CMD_OUT=$(exec_cmd eos-cli1 "eos fileinfo fxid:${FXID_RAIN_DIFF_OVER2} -m --fullpath | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '{if (\$1 ==\"fsid\") {print \$2};}'")
+  # Extract the fxid and local path, trim the input
+  local VECT_FSID=( $(echo "${CMD_OUT}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//') )
+  echo "Used locations: ${VECT_FSID[@]}"
+  local NEW_FSID=""
+  local FST_ONLINE=$(exec_cmd eos-mgm1 "eos fs ls | grep \"online\" | wc -l")
+
+  for (( i=1; i<=${FST_ONLINE}; i++ )); do
+    local found=false
+    for e in ${VECT_FSID[@]}; do
+      if [[ "$i" == "$e" ]]; then
+        found=true
+        break
+      fi
+    done
+    if [[ "${found}" == false ]]; then
+      NEW_FSID=$i
+      break
+    fi
+  done
+
+  if [[ "${NEW_FSID}" == "" ]]; then
+    echo "error: no new FSID found for replication command"
+    exit 1
+  fi
+
+  # Start by tagging the file on the new fst
+  exec_cmd eos-cli1 "eos -r 0 0 file tag ${EOS_RAIN_DIR}/rain_stripe_diff_over2.dat +${NEW_FSID}"
+
+  # Get local path of source and local path of the destination directory
+  local CMD_OUT=$(exec_cmd eos-cli1 "eos fileinfo fxid:${FXID_RAIN_DIFF_OVER2} -m --fullpath | sed -r 's/[[:alnum:]]+=/\n&/g'")
+  local SRC_LPATH=$(echo "${CMD_OUT}" | grep fsid="${VECT_FSID[0]}" -A1 | tail -n1 | sed -r -e 's/^fullpath=//' -e 's/[[:space:]]*$//')
+  local SRC_LDIR=$(echo "${SRC_LPATH}" | sed -r 's/[[:alnum:]]+$//')
+  local SRC_LFILE=$(echo "${SRC_LPATH}" | grep -oE '[[:alnum:]]+$')
+  local DST_LDIR=$(echo "${CMD_OUT}" | grep fsid="${NEW_FSID}" -A1 | tail -n1 | sed -r -e 's/^fullpath=//' -e 's/[[:alnum:]]+[[:space:]]*$//')
+  cp_file_with_xattr_cmd "eos-fst${VECT_FSID[0]}" "${SRC_LDIR}" "${SRC_LFILE}" "eos-fst${NEW_FSID}" "${DST_LDIR}"
+  cp_file_with_xattr_cmd "eos-fst${VECT_FSID[0]}" "${SRC_LDIR}" "${SRC_LFILE}.xsmap" "eos-fst${NEW_FSID}" "${DST_LDIR}"
+
+  # Force resync of fmd on new fst
+  exec_cmd eos-cli1 "eos -r 0 0 file verify fxid:${FXID_RAIN_DIFF_OVER2} ${NEW_FSID} -resync"
+}
+
 # Configure fsck to run more often and reduce the scan times
 function configure_fsck() {
   # First reduce the scan interval on the FSTs
@@ -318,6 +419,8 @@ function check_all_errors_collected() {
     local FOUND_ORPHAN=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_ORPHAN}")
     local FOUND_RAIN_INVALID_STRIPE=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_RAIN_INVALID_STRIPE}")
     local FOUND_RAIN_INVALID_STRIPE2=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_RAIN_INVALID_STRIPE2}")
+    local FOUND_RAIN_DIFF_OVER=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_RAIN_DIFF_OVER}")
+    local FOUND_RAIN_DIFF_OVER2=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_RAIN_DIFF_OVER2}")
 
     if [[ -z "${FOUND_D_MEM_SZ_DIFF}"        ||
           -z "${FOUND_M_MEM_SZ_DIFF1}"       ||
@@ -332,7 +435,9 @@ function check_all_errors_collected() {
           -z "${FOUND_RAIN_STRIPE_SZ}"       ||
           -z "${FOUND_ORPHAN}"               ||
           -z "${FOUND_RAIN_INVALID_STRIPE}"  ||
-          -z "${FOUND_RAIN_INVALID_STRIPE2}" ]]; then
+          -z "${FOUND_RAIN_INVALID_STRIPE2}" ||
+          -z "${FOUND_RAIN_DIFF_OVER}"       ||
+          -z "${FOUND_RAIN_DIFF_OVER2}"      ]]; then
       if (( $((${CURRENT_TIME} - ${START_TIME})) >= ${MAX_DELAY} )); then
         echo "error: some errors not discovered"
         exec_cmd eos-cli1 "eos -r 0 0 fsck report -i -a"
@@ -444,6 +549,8 @@ corrupt_rain_stripe_size
 corrupt_orphan
 corrupt_rain_invalid_stripe
 corrupt_rain_invalid_stripe2
+corrupt_rain_stripe_diff_over
+corrupt_rain_stripe_diff_over2
 
 # Configure fsck to run more often and reduce scan times
 configure_fsck
