TEST: Update eos-extstorage-test with newer import command syntax. Print output of command in import test stage. Add intermediary check in replica move test. Add time step to wait result function. Better exit code reporting

diff --git a/test/eos-extstorage-test b/test/eos-extstorage-test
--- a/test/eos-extstorage-test
+++ b/test/eos-extstorage-test
@@ -39,8 +39,10 @@
 # Usage:
 # eos-extstorage-test <eos_mgm_hostname> [--ssh] [--verbose]
 #    <eos_mgm_hostname> - the name of the MGM host
-#    --ssh              - attempt preparation set-up using ssh
 #    --verbose          - trigger verbose output
+#    --ssh              - attempt preparation set-up using ssh
+#    --no-cleanup       - skip the clean up stage
+#    --only-cleanup     - perform only the clean-up stage
 #
 #------------------------------------------------------------------------------
 
@@ -72,15 +74,15 @@ print_test () {
 }
 
 wait_result () {
-    [[ ${VERBOSE} != false ]] && echo "Waiting ${3} seconds for ${4}"
+    [[ ${VERBOSE} != false ]] && echo "Waiting ${3} seconds for ${5}"
     sleep 2
     COUNT=0
 
     while [[ $(eval $1) -ne ${2} ]]; do
-        sleep 1
-        COUNT=$((COUNT + 1))
-        [[ ${VERBOSE} != false ]] && [[ ${VERBOSE} != "nocount" ]] && echo ${COUNT}
-        [[ ${COUNT} -eq ${3} ]] && echo "error: timeout during ${4}" && return 1
+        sleep ${4}
+        COUNT=$((COUNT + ${4}))
+        ${VERBOSE} && echo ${COUNT}
+        [[ ${COUNT} -eq ${3} ]] && echo "error: timeout during ${5}" && return 1
     done
 
     return 0
@@ -107,6 +109,8 @@ clean_up () {
     eos rmdir /eos/dockertest/${SPACE[1]}/upload/
     eos rmdir /eos/dockertest/${SPACE[1]}/import/
     eos rmdir /eos/dockertest/${SPACE[1]}/
+
+    return 0
 }
 
 #------------------------------------------------------------------------------
@@ -129,7 +133,7 @@ echo $1 | grep ":" &> /dev/null
 EOS_MGM_URL=$1
 CONN_CLIENT=false
 VERBOSE=false
-NOCLEANUP=false
+CLEANUP=true
 
 for arg in "${@:2}"; do
     if [[ ${arg} == "--verbose" ]]; then
@@ -137,7 +141,7 @@ for arg in "${@:2}"; do
     elif [[ ${arg} == "--ssh" ]]; then
         CONN_CLIENT=true
     elif [[ ${arg} == "--no-cleanup" ]]; then
-        NOCLEANUP=true
+        CLEANUP=false
     elif [[ ${arg} == "--only-cleanup" ]]; then
         clean_up
         exit 0
@@ -238,7 +242,7 @@ done
 
 QUERY="davix-ls --s3accesskey ${EOS_FST_S3_ACCESS_KEY} --s3secretkey ${EOS_FST_S3_SECRET_KEY} \
                 --s3alternate --retry 1 ${PATHS[1]}eos/${SPACE[1]}/extfiles/ 2> /dev/null | wc -l"
-wait_result "${QUERY}" 50 60 "S3 upload"
+wait_result "${QUERY}" 50 60 1 "S3 upload"
 [[ $? -ne 0 ]] && exit 1
 
 #------------------------------------------------------------------------------
@@ -256,7 +260,7 @@ done
 
 QUERY="davix-ls --s3accesskey ${EOS_FST_S3_ACCESS_KEY} --s3secretkey ${EOS_FST_S3_SECRET_KEY} \
                 --s3alternate --retry 1 ${PATHS[1]}eos/dockertest/${SPACE[1]}/upload/ 2> /dev/null | grep -v .xattr | wc -l"
-wait_result "${QUERY}" 50 60 "EOS upload"
+wait_result "${QUERY}" 50 60 1 "EOS upload"
 
 EOS_RESULT=`eos -b ls -l /eos/dockertest/${SPACE[1]}/upload/ | wc -l`
 EXT_RESULT=$(eval "${QUERY}")
@@ -272,10 +276,11 @@ fi
 
 ${VERBOSE} && print_test 2 "import operation" "import files from S3 to /eos/dockertest/${SPACE[1]}/import using 'fs import'"
 
-eos fs import ${IDS[1]} ${PATHS[1]}eos/${SPACE[1]}/extfiles/ /eos/dockertest/${SPACE[1]}/import/ &> /dev/null
+OUTPUT=$(eos fs import start ${IDS[1]} ${PATHS[1]}eos/${SPACE[1]}/extfiles/ /eos/dockertest/${SPACE[1]}/import/)
+${VERBOSE} && echo "${OUTPUT}"
 
 QUERY="eos -b ls -l /eos/dockertest/${SPACE[1]}/import/ | wc -l"
-wait_result "${QUERY}" 50 60 "EOS import"
+wait_result "${QUERY}" 50 60 1 "EOS import"
 
 EOS_RESULT=$(eval "${QUERY}")
 ${VERBOSE} && echo "EOS_RESULT=${EOS_RESULT}"
@@ -294,19 +299,25 @@ for i in `seq 0 49`; do
     eos -b file move /eos/dockertest/${SPACE[1]}/import/${i}.dat ${IDS[1]} ${IDS[0]} &> /dev/null &
 done
 
-QUERY="eos -b fs dumpmd $IDS[0] --path | wc -l"
-wait_result "${QUERY}" 50 60 "EOS replica move"
+QUERY="eos -b fs dumpmd $IDS[0] --path | grep /eos/dockertest/${SPACE[1]}/import/ | wc -l"
+wait_result "${QUERY}" 50 60 1 "EOS replica move"
 EOS_RESULT=$(eval "${QUERY}")
+
+if [[ ${EOS_RESULT} -ne 50 ]]; then
+    echo "EOS_RESULT=${EOS_RESULT}"
+    echo "Failed move operation. New replicas were not successfully created."
+    exit 2
+fi
 
 QUERY="davix-ls --s3accesskey ${EOS_FST_S3_ACCESS_KEY} --s3secretkey ${EOS_FST_S3_SECRET_KEY} \
                 --s3alternate --retry 1 ${PATHS[1]}eos/${SPACE[1]}/extfiles/ 2> /dev/null | grep .dat | wc -l"
-VERBOSE="nocount" wait_result "${QUERY}" 0 300 "external storage replica drop"
+wait_result "${QUERY}" 0 300 30 "external storage replica drop"
 EXT_RESULT=$(eval "${QUERY}")
 
 ${VERBOSE} && echo "EOS_RESULT=${EOS_RESULT} EXT_RESULT=${EXT_RESULT}"
 
 if [[ ${EOS_RESULT} -ne 50 ]] || [[ ${EXT_RESULT} -ne 0 ]]; then
-    echo "Failed move operation. Not all replicas were successfully moved."
+    echo "Failed move operation. New replicas created but old replicas were not successfully removed."
     exit 2
 fi
 
@@ -314,5 +325,8 @@ fi
 # Clean-up
 #------------------------------------------------------------------------------
 
-${VERBOSE} && ${NOCLEANUP} && echo "Skipping clean-up step" && exit 0
-${VERBOSE} && echo "Cleaning up" && clean_up && exit 0
+(${CLEANUP} && ${VERBOSE} && echo "Cleaning up") \
+||            (${VERBOSE} && echo "Skipping clean-up step")
+
+${CLEANUP} && clean_up
+exit 0
