TEST: Add test for draindead mode

diff --git a/test/eos-drain-test b/test/eos-drain-test
--- a/test/eos-drain-test
+++ b/test/eos-drain-test
@@ -84,8 +84,6 @@ while [[ $? -eq 0 ]]; do
       eos fs ls | grep " 1 " | grep "drain" | grep "prepare\|draining"
 done
 
-eos fs ls
-sleep 2
 eos fs ls | grep " 1 " | grep "empty" | grep "nodrain"
 
 if [[ $? -ne 0 ]]; then
@@ -100,6 +98,39 @@ if [[ $? -ne 0 ]]; then
       echo "error: failed to put file system in rw mode"
       exit 1
 fi
+
+# Now test the draindead mode, for this we simulate a fmd open error on the
+# targeted file system
+eos node config eos-fst4-test.eoscluster.cern.ch:1095 error.simulation=fmd_open
+eos fs config 4 configstatus=drain
+# Sleep 2 min - 1 for the prepare phase and 1 to give a change to the normal
+# drain to have a go at it.
+sleep 2m
+
+eos fs ls | grep " 4 " | grep "empty" | grep "nodrain"
+
+if [[ $? -eq 0 ]]; then
+    echo "unexpected: file system 4 is drained?!"
+    exit 1
+
+eos fs config 4 configstatus=draindead
+
+eos fs ls | grep " 4 " | grep "draindead" | grep "prepare\|draining"
+
+while [[ $? -eq 0 ]]; do
+      sleep 2
+      eos fs ls | grep " 4 " | grep "draindead" | grep "prepare\|draining"
+done
+
+eos fs ls | grep " 4 " | grep "empty" | grep "nodrain"
+
+if [[ $? -ne 0 ]]; then
+      echo "error: file system 4 is not drained"
+      exit 1
+fi
+
+eos node config eos-fst4-test.eoscluster.cern.ch:1094 error.simulation=none
+eos fs config 4 configstatus=rw
 
 # Remove all the files and directories
 eos rm -rF "/eos/dockertest/drain_test/replica/*"
