TEST: add 'color' functions to eos-instance-test, so they work also on platforms without init.d

diff --git a/test/eos-instance-test b/test/eos-instance-test
--- a/test/eos-instance-test
+++ b/test/eos-instance-test
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 # ----------------------------------------------------------------------
 # File: eos-instance-test
 # Author: Andreas-Joachim Peters - CERN
@@ -46,6 +45,92 @@ export EOS_TEST_TESTTIMESLICE=900
 export EOS_HTTPS_PORT="$(grep -oP 'XrdHttp:\K(\d+)' /etc/xrd.cf.mgm)"
 firsttest=$1
 lasttest=$2
+
+
+################################################################################
+# COLOR FUNCTIONS
+################################################################################
+
+BOOTUP=color
+RES_COL=60
+MOVE_TO_COL="echo -en \\033[${RES_COL}G"
+SETCOLOR_SUCCESS="echo -en \\033[1;32m"
+SETCOLOR_FAILURE="echo -en \\033[1;31m"
+SETCOLOR_WARNING="echo -en \\033[1;33m"
+SETCOLOR_NORMAL="echo -en \\033[0;39m"
+
+echo_success() {
+    [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+    echo -n "["
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
+    echo -n $"  OK  "
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+    echo -n "]"
+    echo -ne "\r"
+    return 0
+}
+
+echo_failure() {
+    [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+    echo -n "["
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+    echo -n $"FAILED"
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+    echo -n "]"
+    echo -ne "\r"
+    return 1
+}
+
+echo_passed() {
+    [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+    echo -n "["
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+    echo -n $"PASSED"
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+    echo -n "]"
+    echo -ne "\r"
+    return 1
+}
+
+echo_warning() {
+    [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
+    echo -n "["
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+    echo -n $"WARNING"
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+    echo -n "]"
+    echo -ne "\r"
+    return 1
+}
+
+# Log that something succeeded
+success() {
+    [ "$BOOTUP" != "verbose" -a -z "${LSB:-}" ] && echo_success
+    return 0
+}
+
+# Log that something failed
+failure() {
+    local rc=$?
+    [ "$BOOTUP" != "verbose" -a -z "${LSB:-}" ] && echo_failure
+    [ -x /bin/plymouth ] && /bin/plymouth --details
+    return $rc
+}
+
+# Log that something passed, but may have had errors. Useful for fsck
+passed() {
+    local rc=$?
+    [ "$BOOTUP" != "verbose" -a -z "${LSB:-}" ] && echo_passed
+    return $rc
+}
+
+# Log a warning
+warning() {
+    local rc=$?
+    [ "$BOOTUP" != "verbose" -a -z "${LSB:-}" ] && echo_warning
+    return $rc
+}
+
 
 ################################################################################
 # Check which version of XRootD we are using
