MGM: GroupDrainer: mark completed groups as drained/drainfailed
This adds a new status string drained/drainfailed to groups and
sets them if we identify all the FSes in the group are drained. We
reuse the GroupStatus enum from earlier instead of a GroupDrainStatus.
This makes it easier to reuse this function to set a generic groupstatus,
however checkGroupDrainStatus function now returns an enum that isn't
exactly mapping to an actual groupstatus but maps well with a groupdrain status.
This direction was chosen for now in favour of having 2 enums with the same
content and similar enum transform functions. Also check the status in
groupdrainer-tests which has a reduced retry_count in the CI to save some time.

Signed-off-by: Abhishek Lekshmanan <abhishek.lekshmanan@cern.ch>

diff --git a/test/eos-groupdrain-test b/test/eos-groupdrain-test
--- a/test/eos-groupdrain-test
+++ b/test/eos-groupdrain-test
@@ -58,6 +58,7 @@ eos space config default space.converter=on
 eos space config default space.groupdrainer=on
 eos space config default space.groupdrainer.threshold=0
 eos space config default space.groupdrainer.retry_interval=10
+eos space config default space.groupdrainer.retry_count=3
 # Create eos directory for tests and copy some files in
 eos mkdir -p /eos/dockertest/drain_test/replica/
 eos mkdir -p /eos/dockertest/drain_test/raiddp/
@@ -142,7 +143,17 @@ done
 
 echo "Drain Complete, FS Status:"
 eos fs ls
+
+echo "Group Status"
 eos group ls
+
+eos group ls | grep -i drained
+
+if [[ $? -ne 0 ]]; then
+    echo "Error: group drain not complete"
+    exit 1
+fi
+
 echo "Setting Group Back to RW"
 eos group set default.1 on
 
