MGM/TEST: Handle replica inconsistency when there is no checksum commited at the mgm, this is treated in the best-effort scenario by issuing a file verify with commit size and checksum. Add test to replicate this situation and check the proper resolution in the eos-fsck-test script. Fixes EOS-6559

diff --git a/test/eos-fsck-test b/test/eos-fsck-test
--- a/test/eos-fsck-test
+++ b/test/eos-fsck-test
@@ -22,8 +22,11 @@ SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 source ${SCRIPTPATH}/eos-test-utils
 
 function usage() {
-  echo "usage: $(basename $0) [--max-delay <sec_delay>] --type docker/local/k8s <k8s_namespace>"
-  echo "  --max-delay : optional max delay in seconds"
+  echo "usage: $(basename $0) [-h|--help] [--max-delay <sec_delay>] [--eos-root <path>] --type docker/local/k8s <k8s_namespace>"
+  echo "  -h, --help  : show this help message and exit"
+  echo "  --max-delay : optional max delay in seconds (default: 300)"
+  echo "  --eos-root  : optional EOS root directory (default: /eos/dockertest)"
+  echo "  --type      : execution environment, one of:"
   echo "       docker : script runs in a Docker based setup"
   echo "       k8s    : script runs in a Kubernetes setup and requires a namespace argument"
   echo "       local  : script runs locally, needs EOS_MGM_URL to be set"
@@ -32,7 +35,6 @@ function usage() {
 # Create and upload test files to the eos instance. We create a random file and
 # upload it multiple times to EOS one file per type of corruption.
 function create_test_files() {
-  EOS_ROOT=/eos/dockertest
   EOS_RAIN_DIR=${EOS_ROOT}/fsck/rain
   EOS_REPLICA_DIR=${EOS_ROOT}/fsck/replica
 
@@ -54,7 +56,8 @@ function create_test_files() {
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_REPLICA_DIR}/file_rep_diff_under.dat &&
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_REPLICA_DIR}/file_rep_diff_over.dat &&
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_REPLICA_DIR}/file_orphan.dat &&
-                     xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_REPLICA_DIR}/best_effort.dat &&
+                     xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_REPLICA_DIR}/best_effort1.dat &&
+                     xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_REPLICA_DIR}/best_effort2.dat &&
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_blockxs_err.dat &&
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_stripe_diff.dat &&
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_stripe_sz_err.dat &&
@@ -62,7 +65,7 @@ function create_test_files() {
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_invalid_stripe_err2.dat &&
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_stripe_diff_over.dat &&
                      xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_stripe_diff_over2.dat &&
-                     xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_invalid_header.dat" 
+                     xrdcp -f /tmp/test_file.dat \${EOS_MGM_URL}/${EOS_RAIN_DIR}/rain_invalid_header.dat"
   FXID_D_MEM_SZ_DIFF=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/file_d_mem_sz_diff.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_M_MEM_SZ_DIFF1=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/file_m_mem_sz_diff1.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_M_MEM_SZ_DIFF2=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/file_m_mem_sz_diff2.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
@@ -74,7 +77,8 @@ function create_test_files() {
   FXID_REP_DIFF_UNDER=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/file_rep_diff_under.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_REP_DIFF_OVER=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/file_rep_diff_over.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_ORPHAN=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/file_orphan.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
-  FXID_BEST_EFFORT=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/best_effort.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
+  FXID_BEST_EFFORT1=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/best_effort1.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
+  FXID_BEST_EFFORT2=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_REPLICA_DIR}/best_effort2.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_RAIN_BLOCKXS=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_RAIN_DIR}/rain_blockxs_err.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_RAIN_DIFF=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_RAIN_DIR}/rain_stripe_diff.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
   FXID_RAIN_STRIPE_SZ=$(exec_cmd eos-cli1 "eos fileinfo ${EOS_RAIN_DIR}/rain_stripe_sz_err.dat -m | sed -r 's/[[:alnum:]]+=/\n&/g' | awk -F '=' '\$1==\"fxid\" {print \$2};' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//'")
@@ -97,7 +101,8 @@ function create_test_files() {
         -z "${FXID_REP_DIFF_UNDER}"       ||
         -z "${FXID_REP_DIFF_OVER}"        ||
         -z "${FXID_ORPHAN}"               ||
-        -z "${FXID_BEST_EFFORT}"          ||
+        -z "${FXID_BEST_EFFORT1}"         ||
+        -z "${FXID_BEST_EFFORT2}"         ||
         -z "${FXID_RAIN_BLOCKXS}"         ||
         -z "${FXID_RAIN_DIFF}"            ||
         -z "${FXID_RAIN_STRIPE_SZ}"       ||
@@ -273,19 +278,65 @@ function corrupt_orphan() {
 }
 
 # Corrupt file that can only be fixed by best-effort
-function corrupt_best_effort() {
+function corrupt_best_effort1() {
   # Get the physical locations of the replicas
-  local CMD1_OUT=$(exec_cmd eos-cli1 "eos -j fileinfo fxid:${FXID_BEST_EFFORT} | jq -r '.locations | .[] | (.fsid|tostring) + \" \" + .fstpath'" | head -n1)
-  local CMD2_OUT=$(exec_cmd eos-cli1 "eos -j fileinfo fxid:${FXID_BEST_EFFORT} | jq -r '.locations | .[] | (.fsid|tostring) + \" \" + .fstpath'" | tail -n1)
+  local CMD1_OUT=$(exec_cmd eos-cli1 "eos -j fileinfo fxid:${FXID_BEST_EFFORT1} | jq -r '.locations | .[] | (.fsid|tostring) + \" \" + .fstpath'" | head -n1)
+  local CMD2_OUT=$(exec_cmd eos-cli1 "eos -j fileinfo fxid:${FXID_BEST_EFFORT1} | jq -r '.locations | .[] | (.fsid|tostring) + \" \" + .fstpath'" | tail -n1)
   count=0
-  set -x
   for line in "${CMD1_OUT}" "${CMD2_OUT}"; do
     local FSID=$(echo ${line} | cut -d ' ' -f 1)
     local LPATH=$(echo ${line} | cut -d ' ' -f 2)
     exec_cmd "eos-fst${FSID}" "echo ${count} >> ${LPATH}"
     count=$((count + 10))
   done
-  set +x
+}
+
+# Corrupt file that can only be fixed by best-effort
+function corrupt_best_effort2() {
+  # Get the physical locations of the replicas
+  local CMD1_OUT=$(exec_cmd eos-cli1 "eos -j fileinfo fxid:${FXID_BEST_EFFORT2} | jq -r '.locations | .[] | (.fsid|tostring) + \" \" + .fstpath'" | head -n1)
+  local CMD2_OUT=$(exec_cmd eos-cli1 "eos -j fileinfo fxid:${FXID_BEST_EFFORT2} | jq -r '.locations | .[] | (.fsid|tostring) + \" \" + .fstpath'" | tail -n1)
+
+  # Make sure both replicas have a valid (non-zero) diskchecksum before
+  # proceeding with the corruption. Otherwise the reset to 00000000 would
+  # be a no-op and the test would not exercise the best-effort repair path.
+  local WAIT_START=$(date +%s)
+  local WAIT_MAX=60
+  while true; do
+    local CHECK_OUT=$(exec_cmd eos-cli1 "eos -r 0 0 file check fxid:${FXID_BEST_EFFORT2}")
+    local DISKXS_VALS=$(echo "${CHECK_OUT}" | awk '{for (i=1;i<=NF;i++) if ($i ~ /^diskchecksum=/) {v=$i; sub(/^diskchecksum=/,"",v); gsub(/"/,"",v); print v}}')
+    local NUM_VALS=$(echo "${DISKXS_VALS}" | grep -c .)
+    local NUM_ZERO=$(echo "${DISKXS_VALS}" | grep -c '^0\+$' || true)
+
+    if [[ "${NUM_VALS}" -ge 2 && "${NUM_ZERO}" -eq 0 ]]; then
+      break
+    fi
+
+    if (( $(( $(date +%s) - ${WAIT_START} )) >= ${WAIT_MAX} )); then
+      echo "error: replicas of best_effort2 do not have a valid diskchecksum"
+      echo "${CHECK_OUT}"
+      cleanup
+      exit 1
+    fi
+    echo "info: waiting for diskchecksum on best_effort2 replicas to be computed"
+    sleep 5
+  done
+
+  count=0
+  # Reset to 0 the checksum and diskchecksum attached to the replicas
+  for line in "${CMD1_OUT}" "${CMD2_OUT}"; do
+    local FSID=$(echo ${line} | cut -d ' ' -f 1)
+    local LPATH=$(echo ${line} | cut -d ' ' -f 2)
+    exec_cmd "eos-fst${FSID}" "eos-fmd-tool modify --path ${LPATH} --field checksum --value 00000000"
+    exec_cmd "eos-fst${FSID}" "eos-fmd-tool modify --path ${LPATH} --field diskchecksum --value 00000000"
+    count=$((count + 10))
+  done
+
+  # Set the namespace checksum also to 0
+  local QDB_CLUSTER=$(exec_cmd eos-mgm1 "cat /etc/xrd.cf.mgm | grep "^mgmofs.qdbcluster" | awk '{print \$2;}'")
+  local QDB_PWDFILE=$(exec_cmd eos-mgm1 "cat /etc/xrd.cf.mgm | grep "^mgmofs.qdbpassword_file" | awk '{print \$2;}'")
+  exec_cmd eos-cli1 "eos-ns-inspect change-fid --no-dry-run --members ${QDB_CLUSTER} --password-file ${QDB_PWDFILE} --fid $(( 16#${FXID_BEST_EFFORT2} )) --new-checksum 00000000"
+  exec_cmd eos-cli1 "eos -r 0 0 ns cache drop-single-file $(( 16#${FXID_BEST_EFFORT2} )) || true"
 }
 
 # Corrupt file to generate RAIN stripe size error
@@ -470,7 +521,8 @@ function check_all_errors_collected() {
     local FOUND_RAIN_DIFF=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_RAIN_DIFF}")
     local FOUND_RAIN_STRIPE_SZ=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_RAIN_STRIPE_SZ}")
     local FOUND_ORPHAN=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_ORPHAN}")
-    local FOUND_BEST_EFFORT=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_BEST_EFFORT}")
+    local FOUND_BEST_EFFORT1=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_BEST_EFFORT1}")
+    local FOUND_BEST_EFFORT2=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_BEST_EFFORT2}")
     local FOUND_RAIN_INVALID_STRIPE=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_RAIN_INVALID_STRIPE}")
     local FOUND_RAIN_INVALID_STRIPE2=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_RAIN_INVALID_STRIPE2}")
     local FOUND_RAIN_DIFF_OVER=$(exec_cmd eos-cli1 "eos -r 0 0 fsck report -i | grep ${FXID_RAIN_DIFF_OVER}")
@@ -491,7 +543,8 @@ function check_all_errors_collected() {
           -z "${FOUND_RAIN_DIFF}"            ||
           -z "${FOUND_RAIN_STRIPE_SZ}"       ||
           -z "${FOUND_ORPHAN}"               ||
-          -z "${FOUND_BEST_EFFORT}"          ||
+          -z "${FOUND_BEST_EFFORT1}"         ||
+          -z "${FOUND_BEST_EFFORT2}"         ||
           -z "${FOUND_RAIN_INVALID_STRIPE}"  ||
           -z "${FOUND_RAIN_INVALID_STRIPE2}" ||
           -z "${FOUND_RAIN_DIFF_OVER}"       ||
@@ -532,12 +585,27 @@ function cleanup() {
 # decoupling docker/kubernetes execution from the test itself
 
 MAX_DELAY=300
+EOS_ROOT=/eos/dockertest
 
-if [[ "$1" == "--max-delay" ]]; then
-  MAX_DELAY=$2
-  shift # past argument
-  shift # past value
-fi
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -h|--help)
+      usage
+      exit 0
+      ;;
+    --max-delay)
+      MAX_DELAY=$2
+      shift 2
+      ;;
+    --eos-root)
+      EOS_ROOT=$2
+      shift 2
+      ;;
+    *)
+      break
+      ;;
+  esac
+done
 
 # Set up global variables
 IS_DOCKER=false
@@ -585,6 +653,7 @@ fi
 
 echo "eos-fsck-test configuration:"
 echo "MAX_DELAY=$MAX_DELAY"
+echo "EOS_ROOT=$EOS_ROOT"
 echo "IS_DOCKER=$IS_DOCKER"
 echo "IS_LOCAL=$IS_LOCAL"
 echo "K8S_NAMESPACE=$K8S_NAMESPACE (if IS_DOCKER=false)"
@@ -611,7 +680,8 @@ corrupt_rain_blocxs_err
 corrupt_rain_stripe_diff
 corrupt_rain_stripe_size
 corrupt_orphan
-corrupt_best_effort
+corrupt_best_effort1
+corrupt_best_effort2
 corrupt_rain_invalid_stripe
 corrupt_rain_invalid_stripe2
 corrupt_rain_stripe_diff_over
@@ -624,9 +694,6 @@ check_all_errors_collected $MAX_DELAY
 # Enable the repair thread
 exec_cmd eos-cli1 "eos -r 0 0 fsck config best-effort on"
 exec_cmd eos-cli1 "eos -r 0 0 fsck config repair on"
-
-# Cleanup the orphan entries
-exec_cmd eos-cli1 "eos -r 0 0 fsck clean_orphans"
 
 # Wait for all the errors to be repaired
 START_TIME=$(date +%s)
@@ -642,6 +709,8 @@ while
       cleanup
       exit 1
     else
+      # Cleanup the orphan entries
+      exec_cmd eos-cli1 "eos -r 0 0 fsck clean_orphans"
       echo "info: sleep for 5 seconds waiting for error repair, `secs_to_human $((${CURRENT_TIME} - ${START_TIME}))` passed"
       sleep 5
     fi
