CI: Template definitions for k8s job tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -111,6 +111,127 @@ before_script:
   allow_failure: true
 
 
+
+.k8s_before_script_template: &k8s_before_script_template
+  before_script:
+    - IMAGE_TAG="${CI_COMMIT_TAG}-${CI_PIPELINE_ID}"
+    - NAMESPACE=$(echo ${CI_JOB_NAME}-${CI_JOB_ID}-${CI_PIPELINE_ID} | tr _ -)
+    - . /home/gitlab-runner/coe-cluster-config/env_st-gitlab-k8s-00.sh # get access configs for the cluster
+    - git clone https://gitlab.cern.ch/faluchet/eos-on-k8s.git
+
+
+.k8s_system_test_script_template: &k8s_system_test_script_template
+  script:
+    - if [[ "$CI_JOB_NAME" == k8s_system_test ]]; then
+        ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -n ${NAMESPACE};
+      elif [[ "$CI_JOB_NAME" == k8s_ubuntu_system_test ]]; then
+        ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -u ubuntu_client_${IMAGE_TAG} -n ${NAMESPACE};
+      elif [[ "$CI_JOB_NAME" == k8s_system_test_qdb ]]; then
+        ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -n ${NAMESPACE} -q;
+      elif [[ "$CI_JOB_NAME" == k8s_system_test_qdb_xt ]]; then
+        ./eos-on-k8s/create-all.sh -i xrd_testing_${IMAGE_TAG} -n ${NAMESPACE} -q;
+      else 
+        echo "CI_JOB_NAME:$CI_JOB_NAME not found"; exit 1;
+      fi;
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) -- /bin/bash -c 'eos vid enable krb5;'
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) -- sed -i 's/eos-mq-test.eoscluster.cern.ch/eos-mq/g' /usr/sbin/eos-instance-test-ci # @todo tmp, then re-code the file
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) -- sed -i 's/eos-fst4-test.eoscluster.cern.ch/eos-fst4.eos-fst4.'"$NAMESPACE"'.svc.cluster.local/g' /usr/sbin/eos-drain-test # @todo tmp, then re-code the file
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) -- eos-instance-test-ci
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) -- git clone https://gitlab.cern.ch/dss/eosclient-tests.git
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) -- /bin/bash -c 'yum install -y at; sudo atd' # workaround for docker exec '-d' flag
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) -- /bin/bash -c 'at now <<< "mkdir /eos1/; mount -t fuse eosxd /eos1/"'
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) -- /bin/bash -c 'at now <<< "mkdir /eos2/; mount -t fuse eosxd /eos2/"'
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) -- /bin/bash -c 'su eos-user; cd /eos1/dockertest/; fusex-benchmark; exit' # workaround for docker exec '-u' flag
+
+.k8s_after_script_template: &k8s_after_script_template
+  after_script:
+    - NAMESPACE=$(echo ${CI_JOB_NAME}-${CI_JOB_ID}-${CI_PIPELINE_ID} | tr _ -) # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character
+    - . /home/gitlab-runner/coe-cluster-config/env_st-gitlab-k8s-00.sh
+    - ./eos-on-k8s/delete-all.sh ${NAMESPACE}
+    - rm -rf eos-on-k8s/
+    - docker images -q | xargs docker rmi || true # remove unused images
+
+
+
+
+
+k8s_system_test:
+  stage: test
+  <<: *k8s_before_script_template
+  <<: *k8s_system_test_script_template
+  <<: *k8s_after_script_template
+  tags:
+    - shell-with-docker
+    - k8s_node
+  allow_failure: true
+  retry: 1
+
+
+# @todo in ubuntu sys test clients must run ubuntu images, with forwardable keytab(?)
+k8s_ubuntu_system_test:
+  stage: test
+  <<: *k8s_before_script_template
+  <<: *k8s_system_test_script_template
+  <<: *k8s_after_script_template
+  tags:
+    - shell-with-docker
+    - k8s_node
+  allow_failure: true
+  retry: 1
+  only:
+    - dev
+    - master
+
+
+k8s_system_test_qdb:
+  stage: test
+  <<: *k8s_before_script_template
+  <<: *k8s_system_test_script_template
+  <<: *k8s_after_script_template
+  tags:
+    - shell-with-docker
+    - k8s_node
+  allow_failure: true
+  retry: 1
+
+
+# @todo use proper xrd_testing_ image, with forwardable keytab(?)
+k8s_system_test_qdb_xt: # xt stands for xrd_testing. Must shorten to not hit HOST_NAME_MAX
+  stage: test
+  <<: *k8s_before_script_template
+  <<: *k8s_system_test_script_template
+  <<: *k8s_after_script_template
+  tags:
+    - shell-with-docker
+    - k8s_node
+  allow_failure: true
+  retry: 1
+  only:
+
+
+k8s_stress_test:
+  stage: test
+  <<: *k8s_before_script_template
+  script: 
+    - ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -n ${NAMESPACE}
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) -- eos chmod 2777 /eos/dockertest
+    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) -- hammer-runner.py --strict-exit-code 1 --gitlab --url eos-mgm.eos-mgm.$NAMESPACE.svc.cluster.local//eos/dockertest/hammer/ --protocols xroot --threads 1 2 10 100 --operations write stat read delete --runs 3 --nfiles 10000
+  <<: *k8s_after_script_template
+  tags:
+    - shell-with-docker
+    - k8s_node
+  allow_failure: true
+  retry: 1
+
+
+
+
+# # @todo must use asan build
+# k8s_unit_test:
+# # @todo must use asan build
+# k8s_namespace_unit_test:
+
+
 clone_docker:
   stage: build:rpm
   image: gitlab-registry.cern.ch/linuxsupport/cc7-base
@@ -369,6 +490,26 @@ cc7_docker_image_commit:
     - tags
 
 
+cc7_asan_docker_image_commit:
+  stage: build:dockerimage
+  tags:
+    - docker-image-build
+  script:
+    - ""
+  variables:
+    TO: gitlab-registry.cern.ch/dss/eos:asan_${CI_PIPELINE_ID}
+    DOCKER_FILE: eos-docker/Dockerfile_asan
+  dependencies:
+    - build_cc7_asan
+    - clone_docker
+  only:
+    - branches
+  except:
+    - beryl_aquamarine
+    - tags
+  allow_failure: true
+
+
 ubuntu_docker_image_commit:
   stage: build:dockerimage
   tags:
@@ -453,28 +594,6 @@ unit_test:
     - build_cc7_asan
   tags:
     - docker_node
-
-
-# @todo must use asan build
-k8s_unit_test:
-  stage: test
-  script:
-    - export IMAGE_TAG="${CI_PIPELINE_ID}"
-    - export NAMESPACE=$(echo ${CI_JOB_NAME}-${CI_PIPELINE_ID} | tr _ -) # a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character
-    - cd /home/gitlab-runner
-    - . coe-cluster-config/env_st-gitlab-k8s-00.sh
-    - kubectl config view; echo "IMAGE_TAG = $IMAGE_TAG"; echo "NAMESPACE = $NAMESPACE"
-    - rm -rf eos-on-k8s
-    - git clone https://gitlab.cern.ch/faluchet/eos-on-k8s.git; cd eos-on-k8s
-    - all_yaml=(eos-storage-*.yaml); for i in ${all_yaml[@]}; do sed -i "s%gitlab-registry.cern.ch/dss/eos.*%gitlab-registry.cern.ch/dss/eos:${IMAGE_TAG}%g" $i; done
-    - ./create-all.sh ${NAMESPACE}
-    - kubectl exec $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) -- eos-unit-tests
-    - kubectl exec $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) -- eos-fst-unit-tests
-    - ./delete-all.sh ${NAMESPACE}
-  allow_failure: true
-  tags:
-    - shell-with-docker
-    - k8s_node
 
 
 namespace_unit_test:
