CI: Moved a big part of 'k8s_system_test_script_template' from .gitlab-ci.yml to a separated script

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -116,7 +116,7 @@ before_script:
     - . /home/gitlab-runner/coe-cluster-config/st-gitlab-k8s-01/env_st-gitlab-k8s-01.sh # get access configs for the cluster
     - NAMESPACE=$(echo ${CI_JOB_NAME}-${CI_JOB_ID}-${CI_PIPELINE_ID} | tr _ -) # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character
     - if [[ "$CI_PROJECT_NAME" == "eos-on-k8s" ]]; then
-        IMAGE_TAG="${BASETAG}773981";
+        IMAGE_TAG="${BASETAG}777552";
         git clone --single-branch --branch ${CI_COMMIT_REF_NAME} https://gitlab.cern.ch/faluchet/eos-on-k8s.git;
       else
         IMAGE_TAG="${BASETAG}${CI_PIPELINE_ID}";
@@ -132,56 +132,14 @@ before_script:
     - docker images -q | xargs docker rmi || true # remove unused images
 
 
-# todo(faluchet) this will be moved in a script
 .k8s_system_test_script_template: &k8s_system_test_script_template
   script:
-    - if [[ "$CI_JOB_NAME" == k8s_system_test ]]; then
-        ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -n ${NAMESPACE};
-      elif [[ "$CI_JOB_NAME" == k8s_ubuntu_system_test ]]; then
-        ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -u ubuntu_client_${IMAGE_TAG} -n ${NAMESPACE};
-      elif [[ "$CI_JOB_NAME" == k8s_system_test_qdb ]]; then
-        ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -n ${NAMESPACE} -q;
-      elif [[ "$CI_JOB_NAME" == k8s_system_test_qdb_xt ]]; then
-        ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -n ${NAMESPACE} -q;
-      else 
-        echo "CI_JOB_NAME:$CI_JOB_NAME not found"; exit 1;
+    - if   [[ "$CI_JOB_NAME" == k8s_system_test ]]; then ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -n ${NAMESPACE};
+      elif [[ "$CI_JOB_NAME" == k8s_ubuntu_system_test ]]; then ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -u ubuntu_client_${IMAGE_TAG} -n ${NAMESPACE};
+      elif [[ "$CI_JOB_NAME" == k8s_system_test_qdb || "$CI_JOB_NAME" == k8s_system_test_qdb_xt ]]; then ./eos-on-k8s/create-all.sh -i ${IMAGE_TAG} -n ${NAMESPACE} -q;
+      else echo "CI_JOB_NAME:$CI_JOB_NAME not found"; exit 1;
       fi
-    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) 
-        -- eos chmod 2777 /eos/dockertest/
-    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) 
-        -- eos vid enable krb5
-    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) 
-        -- sed -i 's/eos-mq-test.eoscluster.cern.ch/eos-mq/g' /usr/sbin/eos-instance-test-ci                                        # @todo tmp, then re-code the file
-    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) 
-        -- sed -i "s/eos-fst4-test.eoscluster.cern.ch/eos-fst4.eos-fst4.${NAMESPACE}.svc.cluster.local/g" /usr/sbin/eos-drain-test  # @todo tmp, then re-code the file
-    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) 
-        -- eos-instance-test-ci
-    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) 
-        -- git clone https://gitlab.cern.ch/dss/eosclient-tests.git
-    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) 
-        -- /bin/bash -c 'atd; at now <<< "mkdir /eos1/; mount -t fuse eosxd /eos1/; mkdir /eos2/; mount -t fuse eosxd /eos2/;"'
-    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) 
-        -- /bin/bash -c 'count=0; while [[ $count -le 10 ]] && ( [[ ! -d /eos1/dockertest/ ]] || [[ ! -d /eos2/dockertest/ ]] ); do 
-              echo "Wait for mount ... $count"; count=$(($count + 1)); sleep 1; done;'
-    - kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) 
-        -- su - eos-user -c 'mkdir /eos1/dockertest/fusex_tests/; cd /eos1/dockertest/fusex_tests/; /usr/sbin/fusex-benchmark' # workaround for docker exec '-u' flag
-    # @todo(esindril): run "all" tests in schedule mode once these are properly supported,\
-    # until then just run the "ci" tests
-    - if [ "$CI_PIPELINE_SOURCE" == "schedule" ]; then
-        kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-mgm) 
-          -- eos vid add gateway "eos-cli1.eos-cli1.${NAMESPACE}.svc.cluster.local" unix;
-        kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) 
-          -- env EOS_FUSE_NO_ROOT_SQUASH=1 python /eosclient-tests/run.py --workdir="/eos1/dockertest /eos2/dockertest" ci;
-      else
-        kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) 
-          -- su - eos-user -c 'python /eosclient-tests/run.py --workdir="/eos1/dockertest /eos2/dockertest" ci';
-      fi
-    - if [ "$CI_JOB_NAME" != k8s_ubuntu_system_test ]; then
-        kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) 
-          -- /bin/bash -c 'eos fuse mount /eos_fuse; eos fuse mount /eos_fuse2;'
-        kubectl exec -n $NAMESPACE -i $(kubectl get pods -n $NAMESPACE --no-headers -o custom-columns=":metadata.name" -l app=eos-cli1) 
-          -- python /eosclient-tests/run.py --workdir="/eos_fuse/dockertest /eos_fuse2/dockertest" ci;
-      fi
+    - ./gitlab-ci/k8s_system_test_script.sh $NAMESPACE
 
 
 clone_docker:
