CI: skip CI pipelines for doc only changes
There are multiple approaches which do this but not quite:
- Adding never as a part of workflow with changes in doc/*/**
  + This doesn't trigger the workflow at all
  ```
  workflow:
  rules:
    - changes:
        - docs/**/*     # Skip pipeline if only docs files are changed
      when: never
    - when: always      # Run pipeline for all other changes
   ```
   However then we can't trigger manual doc jobs as well when needed

- Stopping by failing a pre-job that checks doc only changes
  - If the pipeline is marked as failed, manual jobs may not be run
  - A cleaner way is to write an artifact from the pre-job that will be
  consumed by the build jobs. This is overengineering for such a trivial
  task as one would write env/touch files from the first jobs that build
  jobs check for and then decide
- Cancelling pipelines from within the pre job
  + This is the approach used currently, unfortunately the token
  used is a project token, the issue being that Gitlab CI job
  tokens do not seem to have the power or ability to do this
  https://gitlab.com/gitlab-org/gitlab/-/issues/256089
  + We currently use a project token that has the permissions to do this
  though a more limited token scope is of best interests
  + This job is only triggered when gitlab detects changes in docs/*/** folder
Currently we cancel only for doc/* changes though this is easily
extendible to other directories where we feel builds can be
cancelled. Since builds are only cancelled other jobs can be
re-run if needed

Signed-off-by: Abhishek Lekshmanan <abhishek.lekshmanan@cern.ch>

CI: trigger pre job only for doc changes

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -49,11 +49,26 @@ workflow:
     - if: $CI_COMMIT_TAG
       variables:
         KOJI_SCRATCH: ""
-
-
 #-------------------------------------------------------------------------------
 # Prebuild
 #-------------------------------------------------------------------------------
+doc-skip:
+  stage: .pre
+  script:
+    - |
+      echo "Documentation-only changes detected. Skipping pipeline."
+      # In an ideal world this job failing at the top should not trigger builds
+      # we don't live in that world! In order to avoid creating more complex
+      # dependency graphs, we just cancel the pipeline
+      curl -X POST -H "PRIVATE-TOKEN: $GITLAB_CI_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/cancel"
+      exit 1
+      fi
+  allow_failure: true
+  rules:
+    - changes:
+        - docs/*/**
+      when: always
+    - when: never
 
 .prebuild-template: &prebuild-template_definition
   stage: prebuild
